connector.name=hive
hive.metastore.uri=thrift://localhost:9083
fs.hadoop.enabled=true
hive.config.resources=/opt/hadoop/etc/hadoop/core-site.xml,/opt/hadoop/etc/hadoop/hdfs-site.xml
hive.non-managed-table-writes-enabled=true
hive.storage-format=PARQUET
hive.iceberg-catalog-name=iceberg
hive.delta-lake-catalog-name=delta
hive.hudi-catalog-name=hudi
