data_lab:
  target: duckdb
  outputs:
    duckdb:
      type: duckdb
      path: /home/datalab/runtime/dbt/data_lab.duckdb
      schema: main
      threads: 1
    hive:
      type: hive
      host: localhost
      port: 10000
      schema: default
      threads: "{{ env_var('DBT_HIVE_THREADS', '2') | int }}"
    spark_session:
      type: spark
      method: session
      host: localhost
      schema: default
      threads: "{{ env_var('DBT_SPARK_THREADS', '2') | int }}"
      server_side_parameters:
        spark.master: spark://localhost:7077
        spark.sql.catalogImplementation: hive
        spark.hadoop.fs.defaultFS: hdfs://localhost:9000
        spark.sql.warehouse.dir: hdfs://localhost:9000/hive/warehouse
        spark.hadoop.hive.metastore.uris: thrift://localhost:9083
        spark.sql.hive.metastore.version: 2.3.9
        spark.sql.hive.metastore.jars: builtin
