spark.master                     spark://localhost:7077
spark.scheduler.mode             FAIR
spark.eventLog.enabled           true
spark.eventLog.dir               file:///home/datalab/runtime/spark/events
spark.history.fs.logDirectory    file:///home/datalab/runtime/spark/events
spark.hadoop.fs.defaultFS        hdfs://localhost:9000
spark.sql.warehouse.dir          hdfs://localhost:9000/hive/warehouse
spark.ui.showConsoleProgress     false
spark.sql.catalogImplementation  hive
spark.hadoop.hive.metastore.uris thrift://localhost:9083
spark.sql.hive.metastore.version 2.3.9
spark.sql.hive.metastore.jars    builtin
spark.hadoop.dfs.client.block.write.replace-datanode-on-failure.enable false
spark.hadoop.dfs.client.block.write.replace-datanode-on-failure.policy NEVER
