connector.name=delta_lake
hive.metastore.uri=thrift://localhost:9083
fs.hadoop.enabled=true
hive.config.resources=/opt/hadoop/etc/hadoop/core-site.xml,/opt/hadoop/etc/hadoop/hdfs-site.xml
delta.enable-non-concurrent-writes=true
