#!/usr/bin/env bash

config::apply_profile() {
  local requested_profile="${1:-auto}" requested_category="${2:-all}"
  local override_file spark_core_limit

  config::validate_writable_category "${requested_category}"
  if [[ "${requested_category}" == "all" ]]; then
    requested_category="compute"
  fi
  config::prepare_recommendation "${requested_profile}"
  spark_core_limit="$(config::spark_worker_core_limit)"
  override_file="$(config::override_file)"
  mkdir -p "$(dirname "${override_file}")"

  cat > "${override_file}" <<EOF
# Data Lab runtime overrides
# Generated by datalab_config apply ${requested_profile}
$(config::recommended_env_lines)
EOF

  config::print_heading "Data Lab Config :: Apply"
  config::print_row "Category applied" "$(config::category_title "${requested_category}")"
  config::print_row "Profile applied" "${CONFIG_RECOMMENDED_PROFILE}"
  config::print_row "Override file" "${override_file}"
  config::print_row "Spark worker core limit" "${spark_core_limit}"

  config::print_section "Applied Values"
  config::print_row "Spark app slots" "${CONFIG_RECOMMENDED_SPARK_APP_SLOTS}"
  config::print_row "dbt Spark threads" "${CONFIG_RECOMMENDED_DBT_SPARK_THREADS}"
  config::print_row "dbt Hive threads" "${CONFIG_RECOMMENDED_DBT_HIVE_THREADS}"
  config::print_row "Hive parallel threads" "${CONFIG_RECOMMENDED_HIVE_EXEC_PARALLEL_THREAD_NUMBER}"
  config::print_row "Airflow global tasks" "${CONFIG_RECOMMENDED_AIRFLOW_PARALLELISM}"

  echo
  echo "Guardrail: Spark worker cores can only reach up to ${spark_core_limit} on this container."
  echo
  echo "Restart these services to use the new settings:"
  echo "  datalab_app --restart-airflow"
  echo "  datalab_app --restart-spark"
  echo "  datalab_app --restart-hive"
}
